# Generated by Django 3.1 on 2020-08-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
